### ISSUE TITLE
Clockify Not Logging Hours

### ISSUE THREAD

**Issue by FreeLydia** [microverseinc/microverse-issue-tracker#10]
Please look into the following request from student Deigo Gomes:

hello ok, my clockify record is not appearing inside the my dash.
In the both I'm use the same email: Diego.Gomes87@gmail.com

Do you can help me.

**Comment by digomes87** [comment]
Talking to my group, they informed me that the time appears inside the dash if I install the clokify plug-in in the browser.
I thought that because I use the same email in microverse dash and clokify the data will be filled in automatically.
If in order for the hours to appear inside the dash I have to have installed the plugin, then maybe my report is not an error.

**Comment by FreeLydia** [comment]
Thanks for providing more info, @digomes87! We're looking in to it 💪

**Comment by Keqi** [comment]
@digomes87 I fixed your record. The reason was that your email in the Clockify account was `diego.gomes87@gmail.com` while in any other services you used `Diego.Gomes87@gmail.com`. I guess Clockify transform emails to downcase.

Can you confirm that registered hours is now correct for you?

**Comment by digomes87** [comment]
unfortunately it is still zero in my dash.
<img width="933" alt="Screen Shot 2019-09-11 at 07 29 46" src="https://user-images.githubusercontent.com/5879047/64690150-1b393f00-d466-11e9-984d-1d742e2f39be.png">

and here my account in clock
<img width="677" alt="Screen Shot 2019-09-11 at 07 30 04" src="https://user-images.githubusercontent.com/5879047/64690178-27bd9780-d466-11e9-8fbf-5318cc8bf742.png">

**Comment by Keqi** [comment]
@digomes87 How about now?

**Comment by digomes87** [comment]
Yesssssssss .
Now it's perfect !!!!

**Comment by Keqi** [comment]
Great :)
