### ISSUE TITLE
Project status not changed on "Testing Your Ruby Code - Enumerable" project

### ISSUE THREAD

**Issue by zhuchini** [microverseinc/microverse-issue-tracker#101]
It's a collaborative project and my partner sent a code review and was approved. The status of the project still shows "Request Code Review" on my side.

**Comment by Keqi** [comment]
Hi @zhuchini,

Thanks for the request. Who is your coding partner? I can't find any active partner relationships for you.

**Comment by zhuchini** [comment]
It was Aaron Rory Newbold. He just finished the SQL project and got a new partner.

**Comment by Keqi** [comment]
Hi @zhuchini,

From what I can see, you have submitted a `Project Completion` form for this project and marked it as completed. The scenario which you mentioned in the first post could be caused by your partner checking `I worked solo on this project` checkbox while submitting a Code Review Request.

If you both completed the project and submitted the form, it's all good.
