### ISSUE TITLE
I am always marked as Absent

### ISSUE THREAD

**Issue by Ispirett** [microverseinc/microverse-issue-tracker#102]
I am always marked as Absent, I am always in my meetings but still always marked as absent.
Its currently stating that I am absent everyday last month.

**Comment by Keqi** [comment]
Hi @Ispirett,

Can you send me your email address OR name and surname so I can debug this issue for you?

**Comment by Ispirett** [comment]
ispirett@gmail.com  Isaac Browne

**Comment by Keqi** [comment]
Hi @Ispirett,

You are always marked as absent because your Zoom account uses different email address than the one in the Dashboard.

Dashboard: ispirett@gmail.com
Zoom: i.spirett@gmail.com

Could you please sign out of your Zoom account and always sign in through https://microverse.zoom.us/? This will ask you for your Dashboard credentials and will always sign you in using the correct account.

**Comment by Ispirett** [comment]
Thanks that definitely makes sense. I tried entering credentials manually instead of you google to join but now my zoom account for micoverse is locked  due to failing attempts

**Comment by Ispirett** [comment]
hey @Keqi it's still saying I am absent.

**Comment by Keqi** [comment]
Hi @Ispirett,

Unfortunately, we can not fix your absences for the past. However, since you changed your email, I can see you are no longer absent on team meetings.

If you feel worried or anxious about the potential consequences of your absences, please message the Student Success team and clarify your problem with them linking this Github issue.

**Comment by Keqi** [comment]
Closing as there is not response for 7 days.
