### ISSUE TITLE
I got marked as absent

### ISSUE THREAD

**Issue by alexawesomecode** [microverseinc/microverse-issue-tracker#107]
Hello

I got marked as absent on day 25-10-2019 (Friday). I am pretty sure I signed to the Friday meeting with my partners. You can verify that asking my standup mates.

Thanks!

alexawesomecode@gmail.com

**Comment by Keqi** [comment]
Hey @alexawesomecode,

It seems like your entire team met on Friday for the Stand-Up meeting but in weird hours. You started meeting at `Fri, 25 Oct 2019 13:47:43 CST -06:00` and finished at `Fri, 25 Oct 2019 17:54:55 CST -06:00`.

This is why our system marked you as absent because it couldn't find a meeting within scheduled hours. Did something change to your schedule?

**Comment by alexawesomecode** [comment]
Hello

Yes. I know why I was marked as absent. Two team mates and I were working all the afternoon together, as neither of us had partner at that time (we finished html & css at the same time). So we used the same link that we were using to work together to join the standup team. I think that is why i was marked as absent.  If you can see, we were logged during the standup meeting appointment.

**Comment by mkezmkez** [comment]
we were both present in the stand up meeting,, we clicked the link to join but it just opened the same meetin, I thought by clicking the link and being connected during the meeting was enough. Can you help remove this absence?

Thank you

**Comment by Keqi** [comment]
Hey!

Unfortunately, I can't remove this single absence but you're justified because you explained what you did. Please follow the instructions and join meeting rooms as they appear on the Daily Schedule.
