### ISSUE TITLE
Incorrect absence recorded

### ISSUE THREAD

**Issue by misselliev** [microverseinc/microverse-issue-tracker#115]
Hi! I have two days I'd like to ask to look out please.
![Captura de Pantalla 2019-11-07 a la(s) 17 33 54](https://user-images.githubusercontent.com/32690589/68439451-df300b00-0184-11ea-9fb9-842956f583af.png)

On 11/01 for standup meeting I think it shows up absence because I was the only one in the room (it was a holiday in some countries) and on 11/04 I was being dropped from call at the beginning because of internet connection issues.

Thank you so much for your time! :)

**Comment by Keqi** [comment]
Hi @misselliev,

Unfortunately, we can not unmark you as absent on Nov 1 because Zoom will never record a meeting if there was only one person in the room. If you feel worried or anxious about it, you can clarify the situation with the Student Success team. However, I wouldn't be concerned because in general, you're doing great :)

Nov 4 is sort of similar situation, you'll remain marked as absent but it won't count against you.
