### ISSUE TITLE
Retrospective issues

### ISSUE THREAD

**Issue by misselliev** [microverseinc/microverse-issue-tracker#171]
Hi! I'm unable to submit my retrospective for this week. Says I already uploaded one for this week, which is true because I completely spaced out last week and submitted last week's retrospective this Monday.

**Comment by Keqi** [comment]
Hi @misselliev,

Which `Retrospective Date` have you chosen from the form field? By default, the last Friday is selected and you should always select Fridays for which this Retrospective should have been submitted.

**Comment by misselliev** [comment]
Hi @Keqi ! I used the date that was already set on the form that was 22/11 to submit last week's monday (that was the late form) and then on that friday when form for 29/11 should have been submitted I got that error.
Also checked and it looks like the late form didn't register in dashboard so I'm missing two retrsopectives.
![Captura de Pantalla 2019-12-04 a la(s) 10 37 46](https://user-images.githubusercontent.com/32690589/70166784-a64f5d00-1682-11ea-970f-fc1864edbb7d.png)
![Captura de Pantalla 2019-12-04 a la(s) 10 38 01](https://user-images.githubusercontent.com/32690589/70166785-a6e7f380-1682-11ea-9558-8ba7f1995d6e.png)
![Captura de Pantalla 2019-12-04 a la(s) 10 38 07](https://user-images.githubusercontent.com/32690589/70166786-a7808a00-1682-11ea-87f1-69b77f2c3ace.png)

**Comment by Keqi** [comment]
Hi @misselliev,

Your two most recent retrospectives were submitted as follows:

1.
Retrospective Date: Friday, Nov 15
Submitted at: Mon, Nov 18

2.
Retrospective Date: Friday, Mon 25
Submitted at: Mon, Nov 25

It's very weird that you used pre-selected date `Friday, Nov 22` and I can see in DB that it was saved as `Monday, Nov 25`. That's why your previous week was blocked because there was already a submission. I fixed it manually. You can submit a Retrospective form for the previous week.

Please, use the pre-selected date `Friday, Nov 29` and let me know when you submit it. I want to double-check it again in DB :)

**Comment by misselliev** [comment]
I submitted it with the pre-selected date of Nov 29 and it went smoothly. 
Thank you so much for your help @Keqi, I hope you have an amazing day!

**Comment by Keqi** [comment]
Glad to hear that @misselliev. Thank you :)
