### ISSUE TITLE
My Weekly Progess didnt get to 100% 

### ISSUE THREAD

**Issue by jubaan** [microverseinc/microverse-issue-tracker#172]
I have submitted projects and work around 9 hours every day, but my weekly Progress didn't get to 100%, I want to know why? if it was my fault, want to know what specifically what steps I have to do, so this wont happen again or if it is a Bug Im asking for help to correct the issue.

I'll attach some images with the dashboard view.
![Screenshot from 2019-11-29 21-45-39](https://user-images.githubusercontent.com/25774518/69895227-c6cd8f00-12f1-11ea-9883-34954c46bb0e.png)
![Screenshot from 2019-11-29 21-46-05](https://user-images.githubusercontent.com/25774518/69895228-c7662580-12f1-11ea-9d0f-e326908d6161.png)
![Screenshot from 2019-11-29 21-46-11](https://user-images.githubusercontent.com/25774518/69895229-c7662580-12f1-11ea-8b8f-5876ebf11c5c.png)
![Screenshot from 2019-11-29 21-46-19](https://user-images.githubusercontent.com/25774518/69895230-c7662580-12f1-11ea-8247-d60367c94dde.png)
![Screenshot from 2019-11-29 21-46-39](https://user-images.githubusercontent.com/25774518/69895231-c7febc00-12f1-11ea-9c72-5c4a08c13e72.png)

**Comment by Keqi** [comment]
Hi @jubaan,

You have just discovered a very tiny bug in our Dashboard. This was your first week in the program so you weren't supposed to submit any coding challenge on Monday and that's why your progress bar did not reach 100%. It all should be fine beginning from the next week as you're supposed to submit 4 coding challenges per week.

Don't worry! You're doing great so far :)
