### ISSUE TITLE
Wrong Detected absences

### ISSUE THREAD

**Issue by jabichris** [microverseinc/microverse-issue-tracker#177]
When I go on Attendance & Absences I am seeing absences that has been detected yet I have attended all the sessions and logged everything that was supposed to be submitted.

**Comment by Keqi** [comment]
Hi @jabichris,

Indeed. We have discovered that our system stopped asking students to sign in before they join the meetings. You signed in as a guest recently and that's why the system marked you as absent.

This won't be counted against your progress. Please, consult it with the Student Success team to justify your case and link this issue in the Zendesk ticket.

Thank you!
