### ISSUE TITLE
Wrongly detected absence 

### ISSUE THREAD

**Issue by sz16900** [microverseinc/microverse-issue-tracker#179]
I raised an issue a few days ago about been detected as absent. The issue hasn't been solved and I recently got a newly detected absent.

**Comment by Keqi** [comment]
Hi @sz16900,

Can you send me your email address so I can debug your issue? We had a short failure in our system and students could join as guests to meetings which effectively stopped matching them to their records. It shouldn't be happening anymore. Please let me know if you still being marked as absent for the next couple of days.

**Comment by sz16900** [comment]
Hi there:

My email is zea.seth@gmail.com

I took a screenshot of the issue...

It still marks me as absent and it did it again yesterday...

Thank you,
Seth Zea

**Comment by Keqi** [comment]
Hi @sz16900,

As far as I can see, you joined to these meetings as a guest and that's why our system couldn't match you. Our Zoom setting to force users to be signed-in before they join the call was temporarily disabled but it was turned on again. I can see you joined your meetings signed in to Zoom yesterday (Dec 4). It all should be fine from now.

Please, contact the Student Success team to justify your false absences from the past. I can see in the system that you attended all meetings.

Thank you!

**Comment by sz16900** [comment]
Than you so much for taking care of this issue, have a great day.
