### ISSUE TITLE
E-mailed my address with details but issue was closed 

### ISSUE THREAD

**Issue by Jhdezj** [microverseinc/microverse-issue-tracker#193]
Hello there, issue #162 (I have a false detected absence) was closed due to no response for 7 days but I actually sent an e-mal to maciej.nowak90 at gmail with details about my case.
![False detected absense](https://user-images.githubusercontent.com/50807102/70613372-bc4ea780-1bc5-11ea-8948-2779ed20bbfb.png)

**Comment by uzorjchibuzor** [comment]
Hello @Jhdezj ,

I am taking this that the absence recorded for you was for November 27, 2019? Kindly let us know the meeting you were marked absent for. Thanks

**Comment by Jhdezj** [comment]
Hello! Thanks for the reply. 
No, the absence recorded was on 2019-11-26. 
![absence](https://user-images.githubusercontent.com/50807102/71026283-25eb1c00-20c6-11ea-9093-b90a54a4f9a2.png)

**Comment by Keqi** [comment]
Hi @Jhdezj,

I am extremely sorry for the very long response time. Our Dev team resources are very limited recently.

I've fixed this record for you. It was caused by the fact that you joined as a guest and we couldn't recognize you in the system. Is there anything else we can do for you?

Please, feel free to close this issue.

**Comment by Jhdezj** [comment]
Hey, thanks for the reply. I just checked the attendance record and my absence is gone.  That's all I needed. Thanks again.
