### ISSUE TITLE
Detected Absences

### ISSUE THREAD

**Issue by cliftondavies** [microverseinc/microverse-issue-tracker#211]
I noticed a series of absences on my dashboard when this is not the case. I have been absent once, for the Standup Meeting on 2019-12-18.
Please could you look into this. I hope to hear from you soon.

![screencapture-dashboard-microverse-org-absences-2019-12-27-17_53_54](https://user-images.githubusercontent.com/20408665/71527361-f660be80-28d2-11ea-83a0-a09be881a1f0.png)

**Comment by Keqi** [comment]
Hi @cliftondavies,

I am extremely sorry for the very late response. Our development resources are very limited recently.

Your absences have been manually withdrawn. You were marked as absent because you joined these meetings as a guest and our system couldn't recognize you. Afterward, we enabled the option in Zoom to impose sign-in state from users and that's when you stopped seeing absences in your Dashboard. I am sorry, I hope it won't happen again.

**Comment by cliftondavies** [comment]
Thank you, @Keqi.
