### ISSUE TITLE
False absence detected

### ISSUE THREAD

**Issue by trekab** [microverseinc/microverse-issue-tracker#243]
I have just noticed a wrong absence on my dashboard(2020-01-21). I have no idea how this happened since I was present at that meeting.

**Comment by Keqi** [comment]
Hi @trekab,

It seems like you were present at this meeting alone. Is this correct? In such a case, our system does not save the meeting record and everyone is marked as absent because there have to be at least 2 participants.

Please, reach out to the Student Success team and explain the problem. You can use the link to the GH issue. They will create an absence request for you.
