### ISSUE TITLE
Microverse Dashboard > Incorrect "Action Required" Alert

### ISSUE THREAD

**Issue by moinkhanif** [microverseinc/microverse-issue-tracker#245]
Hey team,

With the recent inclusion of the Capstone project for the HTML/CSS section, the dashboard keeps asking us to complete the grid-based layout project to complete the HTML/CSS section. But the section is complete for me. My capstone project was reviewed and accepted.

I get the following alert message:

![Annotation 2020-01-30 041350](https://user-images.githubusercontent.com/6555800/73411223-96729300-432a-11ea-9bec-5f09b63a6693.png)

And it redirects to the [projects_progress page](https://dashboard.microverse.org/projects_progress) which shows that my progress is incomplete without the Grid layout project.

![Annotation 2020-01-30 041437](https://user-images.githubusercontent.com/6555800/73411252-b99d4280-432a-11ea-91a7-79f43c778e89.png)

Kindly advise as to what needs to be done in this situation.

Thank you.

**Comment by Keqi** [comment]
Hi @moinkhanif,

Nice catch. @nidalaa @gootyfer do you think we should remove the last HTML project from the Dashboard?

**Comment by nidalaa** [comment]
@Keqi we cannot remove this project yet because of the students who completed it in the past.

However, thank you for your report @moinkhanif 🙇‍♀ 
I made sure that this project is marked as deprecated on the projects list - you can see it on your progress page. Please ignore `Projects actions required` in `My progress` section for the time being. We will fix it as soon as capstone projects are incorporated into progress list :)
