### ISSUE TITLE
Quicksort 1 test case

### ISSUE THREAD

**Issue by Oluwadamilareolusakin** [microverseinc/microverse-issue-tracker#249]
# Description
Hello team! Going through the [quicksort1](https://repl.it/student/submissions/10611813) challenge on Repl.it, I discovered a possible flaw in the test case. I have put together a little illustration to detail how I imagine the program should run and the expected end result for the test case. Please consider them below:

### Test case
partition([4, 5, 3, 9, 1])  Expected:  => [3, 1, 4, 5, 9] Actual: => [1, 3, 4, 9, 5]

### My explanation
Step 1: 
We start the program with the "unsorted array". We initialize 3 variables, one to help loop through the array(currentIndex), one to keep track of the final location where we'll put our pivot(swapIndex), and our pivot element.
![screenshot](https://images2.imgbox.com/0f/c6/I8ii3oD1_o.jpeg)

Step 2:
We start looping and comparing each element to the pivot element in size. If an element is less than the pivot, we increment the swapIndex, and swap that element(that is less than the pivot) with the element in the swapIndex's location.
![screenshot](https://images2.imgbox.com/fc/85/4y8pvQ0p_o.jpeg)

Step 3:
Finally, we can see the swap in action, because 3 is less than 4(our pivot)
![screenshot](https://images2.imgbox.com/51/b1/VNNsW5Oe_o.jpeg)

Step 4:
We keep looping in search of another element less than 4
![screenshot](https://images2.imgbox.com/35/d2/EeeHK5ka_o.jpeg)

Step 5:
We finally come upon another element less than the pivot so we swap AGAIN
![screenshot](https://images2.imgbox.com/4c/77/9ZkLZaTi_o.jpeg)

Step 6:
We reach the final element in the array and now comes the time to move the pivot element into its rightful spot!
![screenshot](https://images2.imgbox.com/5f/33/fm4kATwE_o.jpeg)

Step 7:
We obtain the final array
![screenshot](https://images2.imgbox.com/df/bd/8AONbSgO_o.jpeg)

### Summary
This is how I think it should work ideally and I welcome any criticism or suggestions/corrections if I am wrong.

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by gootyfer** [comment]
Hi @Oluwadamilareolusakin ,

I think that for quicksort, the approach that you are following about swapping values does not work. As far as I can read in the challenge definition in replit `The array should otherwise remain in the same order.`. This means that for the input `[4, 5, 3, 9, 1]` the output after 1 step of quicksort is `[3, 1, 4, 5, 9]`. I think that to solve this challenge you should follow this approach:
1. take the pivot (4) out of the array
2. create 2 new arrays, one for lower and one for higher values
3. compare the rest of the values in the original array to the pivot: if lower or equal, push it to lower array; if higher, push it to higher array. 
4. Merge lower array + pivot + higher array, and this is the solution

In this way, the elements keep that same order that we had in the original array. For example, in the original array 3 had a lower index than 1; and this keeps for the solution.

Can you understand the approach? What do you think about it?

**Comment by Oluwadamilareolusakin** [comment]
Hello Israel, 


I've given this a lot of thought and I understandyour approach.  However, with the idea behind quicksort, this will quickly deviate from that and turn into an algorithm similar to merge sort.


The first part of quicksort is supposed to return the swapIndex (rightful position for our pivot). It is little about keeping the order of the array and more about finding the right position(index) for the pivot element.


Do you mind taking a second look at my illustration and maybe meeting with me on a zoom call to discuss this jn real-time? I am positive I will benefit from talking to you, if that is okay.


I look forward to hearing from you. 


Many Thanks,
Best Regards, 
Dami.




---- On Tue, 04 Feb 2020 16:18:52 +0100 notifications@github.com wrote ----



Hi @Oluwadamilareolusakin ,

I think that for quicksort, the approach that you are following about swapping values does not work. As far as I can read in the challenge definition in replit The array should otherwise remain in the same order.. This means that for the input [4, 5, 3, 9, 1] the output after 1 step of quicksort is [3, 1, 4, 5, 9]. I think that to solve this challenge you should follow this approach:

take the pivot (4) out of the array
create 2 new arrays, one for lower and one for higher values
compare the rest of the values in the original array to the pivot: if lower or equal, push it to lower array; if higher, push it to higher array.
Merge lower array + pivot + higher array, and this is the solution

In this way, the elements keep that same order that we had in the original array. For example, in the original array 3 had a lower index than 1; and this keeps for the solution.

Can you understand the approach? What do you think about it?

**Comment by gootyfer** [comment]
Hi @Oluwadamilareolusakin ,

As you said, I think it's better if we discuss this issue in a sync call and post here the results. I'll contact in a private message to follow up.

Best,
Israel

**Comment by gootyfer** [comment]
Hi @Oluwadamilareolusakin ,

I will give you more context so that my answer got understood.

In challenges 7.9 and 7.10 the idea is that you understand the concepts behind quicksort. For that reason, a naive approach of the algorithm is presented and that is the one we ask you to follow in these coding challenges. The simple approach is to use sub arrays for sorting. But challenge 7.11 introduces a more complex solution for quicksort, where you need to sort using the same array and there comes the *swapping* and your approach is totally fine. 


I think that the problem here is about expectations:
- in challenges 7.9 and 7.10 we expect that you implement the naive approach, not using swapping
- in challenge 7.11 we expect you to implement the complex approach using swapping

I hope this is more clear now :) Otherwise, make me know!
Best regards,
Israel
PS: I didn't say before, but your explanation with illustrations is really really nice! Good job!
