### ISSUE TITLE
Wrong detected absences

### ISSUE THREAD

**Issue by Flakster** [microverseinc/microverse-issue-tracker#256]
I've been erroneously marked as absent in several sessions, but up to this day, my only absences have been informed in advance via the absence request form. I sent an email with this issue to the Student Success office, and they told me to raise this issue here, so I kindly ask you to review it.

![absences1](https://user-images.githubusercontent.com/53324035/74072632-65066100-49d5-11ea-858d-abab3e4db557.png)

**Comment by Keqi** [comment]
Hi @Flakster,

**January 21** - It may sound weird but our system did not see you in this meeting. Do you remember if joined the right call or if you had some problems attending this meeting? (connectivity issues, Zoom errors?)

**Novemeber 26,27** - I fixed it for you. Those absences were there because you joined the meeting as a guest and our system couldn't find you in the database. It shouldn't be a problem anymore as we're enforcing sign-in state before students join the call.

**Comment by Flakster** [comment]
On January 21 I Joined the stand up meeting using the link in my Dashboard. No one else joined, but then my partners told me that in fact, they attended.

**Comment by Keqi** [comment]
@Flakster If none else was in the meeting, I'll need you to reach out to the Student Success team and ask to create a past absence request for you. If there is only one person in the meeting room, the record is not saved and therefore everyone is marked as absent. This is a flaw in the system and we're working to fix it.

**Comment by alvp01** [comment]
I have some registered absences for 18 and 19 of February but I attended those meetings @Keqi 
![photo_2020-02-20_10-17-36](https://user-images.githubusercontent.com/54279503/74945879-d5968000-53ce-11ea-9fee-c5ff7bd96636.jpg)

**Comment by Keqi** [comment]
Hi @alvp01,

Please, create a separate issue for your problem. Thanks :)

**Comment by Keqi** [comment]
Closing this issue as there is no response from owner for more than 7 days. Please, re-open if this needs further discussion.
