### ISSUE TITLE
catch up fridays 

### ISSUE THREAD

**Issue by oscardelalanza** [microverseinc/microverse-issue-tracker#29]
each friday the coding challenge is marked as past due in the dashboard, and the progress never goes up than 90%, may be is not a bug, but i guess is a good idea modify the friday coding challenge tag or just avoid the past due that day

**Comment by Keqi** [comment]
Hi @oscardelalanza,

Thanks for your report. We'll look into that issue.

**Comment by Keqi** [comment]
Hey @oscardelalanza,

Quick question: How do you submit your coding challenge? Do you click on the button in the calendar or do you go through `/forms` page?

**Comment by rna** [comment]
Hi @Keqi 

Friday mornings first hour are supposed to be catch-up sessions instead of regular coding challenge according to the timesheet. But the dashboard calendar not reflecting the same, It's showing as a coding challenge. Since we are not doing coding challenge on Friday, every week progress is not reaching 100%.

@oscardelalanza I believe this is the issue. Correct me if I'm wrong.

@Keqi 
- We are submitting the forms through the dashboard. 
- Though we can submit the past due coding challenge on next day, we'll always due by one challenge,
- Tell me if we both were wrong for not doing the challenge on Friday. If not, I suggest this improvement.

**Comment by oscardelalanza** [comment]
@rna that's correct!

**Comment by Keqi** [comment]
Thanks for a wide explanation @rna. Is there anything we can change in the process @FreeLydia? Perhaps we should stop count Friday coding challenges to weekly progress?

**Comment by FreeLydia** [comment]
Thanks @oscardelalanza and @rna 

@Keqi - Here's what we can do, please create GH issues for the following:

<img width="913" alt="Screen Shot 2019-10-09 at 9 54 22 AM" src="https://user-images.githubusercontent.com/47569337/66466810-399d5500-ea7b-11e9-82f8-e500234d45fd.png">

1. Change the copy to "Catch-Up Friday." 
2. When it's Friday, change the copy on the action button to "Nothing Due" and keep it greyed out.
3. Add an (i) icon next to the date, and link it to [this School Announcement.](https://microverse.zendesk.com/hc/en-us/articles/360034115574-Introducing-Catch-Up-Friday-s-)

<img width="872" alt="Screen Shot 2019-10-09 at 9 54 39 AM" src="https://user-images.githubusercontent.com/47569337/66466954-79643c80-ea7b-11e9-9268-12c54b8ced9d.png">

4. Change the calculation for the Progress bar to be out of 9, not 10.

**Comment by Keqi** [comment]
Hi @oscardelalanza @rna,

We have just deployed changes to the Dashboard which reflect new requirements. Fridays will be dedicated to catch-up with the current workload and to submit a retrospective form.

Thank you all for your honest feedback and detailed insight into the problem :)
