### ISSUE TITLE
No Join call button for the Collaborative coding Sessions

### ISSUE THREAD

**Issue by gregthepeg4** [microverseinc/microverse-issue-tracker#305]
This thread is for Shubham to be able to follow up directly about his join call button issues with the dev team.

**Comment by shubham14p3** [comment]
Hi Everyone,
I have Signed in Using microverse.zoom.us  (As per instruction given on On-boarding),
Also I am sharing the screenshot for the same in the Mail for your understanding.

Note : Both my personal mail & Microverse name have same Email ID

**Comment by Keqi** [comment]
Hi @shubham14p3,

I checked it again today in the Microverse Zoom dashboard and it seems like your account has just been connected. It is possible that you might have been logged in through Gmail or standard account to Zoom before and recently you switched your accounts because I haven't seen your account in Zoom prior to that.

Anyways, from now on, you should see a link to the collaborative sessions in Dashboard :)

Thanks for your patience.

**Comment by shubham14p3** [comment]
Thanks, I can see the join in call as well.
