### ISSUE TITLE
Optional fields for new completion form are incorrect and a reviewer names list suggestion

### ISSUE THREAD

**Issue by oscarnava** [microverseinc/microverse-issue-tracker#31]
The new project completion form requires the optional live version link and the dislikes when they should be optional.

Also, do something about the reviewer list, because whenever I want to locate the name from the reviewer Github's nickname I always have to guess. Including this nickname on the list would be very helpful.

**Comment by Keqi** [comment]
Hey @oscarnava,

Optional fields should be fixed next week. We have just discovered that. Although, we tend to encourage students to fill all fields. We'll get rid of validation for live project link because message explicitly says it's optional but dislikes will be left as is.

Unfortunately, we don't store Github nicknames in our database so we can't add them to the select. However, you can look up TSE name and surname in his GH profile and then find him in the select.

**Comment by Keqi** [comment]
We have removed validation from `live_project` field. It's in production.
