### ISSUE TITLE
Several absences, mostly in the morning sessions

### ISSUE THREAD

**Issue by Oluwadamilareolusakin** [microverseinc/microverse-issue-tracker#35]
Hi, My name is Tolulope Olusakin - oluwadamilareo@fixus.com.ng, I am experiencing issues with the way my attendance is being tracked, I've not missed any meetings and now I have several absences showing up in my dashboard with a long streak of missed morning meetings. I'd love if this can be rectified

**Comment by Keqi** [comment]
Hi @Oluwadamilareolusakin,

It seems like you joined meetings from your phone a couple of times and you didn't sign in to the Zoom. You were present on meetings as a guest and that's why our system couldn't detect you.

Can you make sure you sign in to microverse.zoom.us before you join any meeting?

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
