### ISSUE TITLE
Several Absences

### ISSUE THREAD

**Issue by majovainilla** [microverseinc/microverse-issue-tracker#53]
I have multiple absences in my dashboard.

I have only missed one call without requesting an absence and that would be the stand-up meeting in august 30th.

Before the announcement, I don't think I joined the microverse zoom account, so that's probably why I have so many absences (but still some days are marked as present).

After the announcement, I check every day for the link to be microverse.zoom and if it's not, then I close the window and click the "Join call" again.

Can you help me? My email is maria_reyes@me.com

Thanks!

**Comment by Keqi** [comment]
Hi @majovainilla,

Indeed, you have lots of absences in your dashboard but most of them are because you joined meetings as a guest. I can see that from Sept 14, you are following instructions and were not marked as absent any day.

Don't worry about these past "absences". They won't be counted against you. We're working to fix history and start your afresh :)

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
