### ISSUE TITLE
Cannot submit the Weekly Retrospective Form

### ISSUE THREAD

**Issue by MauricioRobayo** [microverseinc/microverse-issue-tracker#70]
Yesterday I tried to submit the Weekly Retrospective form but I got the following error:

```
Restrospective was already submitted for this week.
```

I didn't try anymore yesterday thinking it might be a temporary issue, so I tried again today to see if I could. But got the same error:

![image](https://user-images.githubusercontent.com/2121481/65819536-91b69a80-e1e3-11e9-86c6-6aa02deca6b7.png)

## I noticed the following:

1. I tried filling the date with different dates but it always comes back to me with today's date and the same error.
2. On Thursday I forgot to send the Daily Stand form, so I got the email on Friday reminding me to send it. I check the link on the email and when I opened the form through that link, the form date defaults to today's date, not to the date I was missing the form.
3. I haven't got any email reminding me to send the missing Weekly Restrospective Form.

## My guess:

When I used the link in the email to submit the Daily Stand Up form for Thursday (the day I forgot to send it), the form date was prefilled with Friday's date (the day I sent that form). So I guess the Daily Stand Up form from Thursday was stored or registered with Friday's date, therefore I cannot submit the Weekly Retrospective form since there is already a form with Friday's date stored someplace (although its a Daily Stand Up form).

## Related issue:

On the dashboard, I keep getting the Weekly Retrospective as `Past Due`, but I cannot submit the corresponding form with that date because of the initially reported issue.

![image](https://user-images.githubusercontent.com/2121481/65819695-2d94d600-e1e5-11e9-84d4-ae3610903b5e.png)

**Comment by Keqi** [comment]
Hi @MauricioRobayo,

Thanks for your wide explanation. I wish every student explained a problem with such level of details as you. I am impressed :)

To the point:

I see you submitted the Retrospective on Monday 23 September and you set the date in the date-picker to the same day. I suppose you submitted it on Monday because you received an email reminder.

In the `Retrospective Date` date-picker you should always choose Friday on which this retro should have been submitted. For example:

You forgot to submit your Retrospective on Friday, Sept 20. You received an email reminder. You should go to the form, fill it out and select Friday, Sept 20 as a `Retrospective Date` as this was a due date for this submission.

The validation fails for you because the system sees that you have already submitted a Retro for this week, even though it was Monday, not Friday. We'll fix it :)

Please, let me know if this clarifies your problem. I am happy to help.

**Comment by MauricioRobayo** [comment]
Great! Thanks, @Keqin. Got it, your explanation makes sense to me 👍 .
