### ISSUE TITLE
Incorrect absence recorded

### ISSUE THREAD

**Issue by shadymedy** [microverseinc/microverse-issue-tracker#8]
The system flagged me as absent yet I was present.

I noticed that will have to log in for the system to mark us present but I at times when joining Stand-Up Team, the system will not required us to log in,  is there anything can be done about that.

**Comment by Keqi** [comment]
Hey @shadymedy,

I checked in the logs and on `2019-09-09` and `2019-09-06` system did not see you in the meetings, even as a guest. Is that correct?

The system might not ask you to sign in because you are already signed in. Can you double-check if you are signed-in before joining the standup call?

**Comment by Keqi** [comment]
We have cleared out absences before September 17, 2019. You can read more about it in the announcement: https://microverse.zendesk.com/hc/en-us/articles/360036272593

If you still see false absences, please create new GH issue describing a problem :)
